### ISSUE TITLE
Weapons not rendering in hands

### ISSUE THREAD

**Issue by StainedTerra** [Truly-Modular/Modular-Item-API#10]
**Describe the bug**
Items were not rendering within the hand (have tested on a new modpack and it works fine, so I can confirm that it is most likely a mod incompatibility)

**To Reproduce**
unknown will attach log below
[latest.log](https://github.com/Truly-Modular/Modular-Item-API/files/13245459/latest.log)
 

**Expected behavior**
Weapons to render in the hand but they don't

**Screenshots**
![2023-11-03_09 43 22](https://github.com/Truly-Modular/Modular-Item-API/assets/103166873/97b90303-e8e9-4e7b-ba22-cefd46b7879b)
![2023-11-03_10 02 59](https://github.com/Truly-Modular/Modular-Item-API/assets/103166873/32eafcb0-8686-4a59-b190-9a0f04468da3)

**Minecraft and Mod Version:**
Minecraft: 1.20.1
Forge/Fabric: Fabric
Miapi: 1.0.3

**Additional context**
Will continue to debug on my end and update if I find what's causing it

**Comment by Smartin-b** [comment]
Iris is at fault. Remove/Disable Iris and restart.
https://github.com/IrisShaders/Iris/blob/1.20.1/docs/development/compatibility/core-shaders.md

**Comment by StainedTerra** [comment]
> Iris is at fault. Remove/Disable Iris and restart. https://github.com/IrisShaders/Iris/blob/1.20.1/docs/development/compatibility/core-shaders.md

yup that was it. any plans to have compatibility down the line?

**Comment by Smartin-b** [comment]
Well, i would implement compat, but iris has no way of allowing Mods to implement shaders. 
And we cant render our items without custom shaders. 
So, sadly no, its not on my hands to implement compat.

**Comment by StainedTerra** [comment]
I thought as much, all good though great mod nonetheless ill probably try a survival playthough with it later down the line lol

**Comment by CyaniideDrive** [comment]
Is there a shader mod that does work with the mod currently?

**Comment by Smartin-b** [comment]
truly modular now has a fallbackrendermode to combat this, but it severly decreases visual quality
