### ISSUE TITLE
Using the mod in a server causes a NoSuchFieldError

### ISSUE THREAD

**Issue by EggMuncherSupreme** [Truly-Modular/Modular-Item-API#11]
**Describe the bug**
Using the Modular Workbench on a server causes a NoSuchFieldError to occur, resulting in being kicked to the home screen.

**To Reproduce**
1. Set up a server as normal
2. Add Truly Modular to the server's modlist
3. Make and place down a Modular Workbench
4. Create a new tool/armour piece or edit an existing one

**Expected behavior**
It should have proceeded as it should in singleplayer, but it instead kicks me from the server.

**Screenshots**
<img width="568" alt="image" src="https://github.com/Truly-Modular/Modular-Item-API/assets/48143527/c2ef75c4-e022-402e-a696-3ed9021f70d2">

**Minecraft and Mod Version:**
Minecraft: 1.20.1
Forge/Fabric: 47.1.3
Miapi: 1.0.3
other: Archery, Arsenal, Armory 1.0

**Comment by Smartin-b** [comment]
can you send the log file?

**Comment by Smartin-b** [comment]
can you test if the issue still persists with?
https://cdn.discordapp.com/attachments/1098169086275489823/1171187833327865936/Truly-Modular-miapi-1.0.4-1.20.1-fabric.jar?ex=655bc4ab&is=65494fab&hm=16f32e104de336814a4d4722ad3e1411cdca38e770477bb29842a9860e6c4d1e&
im having trouble download mojangs server rn...

**Comment by EggMuncherSupreme** [comment]
> can you send the log file?

[latest.log](https://github.com/Truly-Modular/Modular-Item-API/files/13273255/latest.log)

**Comment by EggMuncherSupreme** [comment]
> can you test if the issue still persists with? https://cdn.discordapp.com/attachments/1098169086275489823/1171187833327865936/Truly-Modular-miapi-1.0.4-1.20.1-fabric.jar?ex=655bc4ab&is=65494fab&hm=16f32e104de336814a4d4722ad3e1411cdca38e770477bb29842a9860e6c4d1e& im having trouble download mojangs server rn...

I use forge, do you have a forge version? I would use Connector but that just another potential factor.

**Comment by Smartin-b** [comment]
My internet refused to donwload the original server jar, but thats fixed now.
After some additional investigation, it works with forge 41.0.X, but not with forge 41.1.3 or higher. ill try to get a fix, but there just is nothing in the logs explaining where the hell the issue comes from, you can try using the fabric jar with connector, that might work.

**Comment by EggMuncherSupreme** [comment]
> Try this jar: [https://cdn.discordapp.com/attachments/1098169086275489823/1171261421498159208/Truly-Modular-miapi-1.0.4-1.20.1-forge.jar?ex=655c0933&is=65499433&hm=a5e46bfe97b80670eb1a04b1d58159948277fbada7372a00e70d4edf641f0d9a&](url)
> 
> In my testing it was fixed, but you can never be too sure.

As far as I can tell, it seems resolved as well
