### ISSUE TITLE
Cannot invoke because ATTACK_RANGE is null

### ISSUE THREAD

**Issue by oinkratpig** [Truly-Modular/Modular-Item-API#12]
**Describe the bug**
Crash upon trying to add a blade to a weapon in a server. Seems to happen with any combination (blade, handle, etc.). Does not crash when used in singleplayer.

**Screenshots**
https://i.imgur.com/87v4WL4.png

**Minecraft and Mod Version:**
Minecraft: 1.20.1
Forge/Fabric: Forge 47.1.3
Miapi: 1.0.4

**Additional context**
Using [many other mods](https://pastebin.com/Xcp2HkKQ). Tried with and without Oculus installed. Unfortunately, since it's not a "true" crash the logs didn't seem helpful (I couldn't find anything related to the mod).

**Comment by Smartin-b** [comment]
hm, i think i understand the issue even without logs, can you try if this jar fixes the issue?
https://cdn.discordapp.com/attachments/1098169086275489823/1172550257075306497/Truly-Modular-miapi-1.0.5-1.20.1-forge.jar?ex=6560b986&is=654e4486&hm=5a7c766a895ac6a3351b64ff1cd3094c25be6aa2a86859b116e4802ecb6dfd14&

**Comment by oinkratpig** [comment]
There are [no options for creating weapons/tools now](https://i.imgur.com/mjp40tm.png).

**Comment by Smartin-b** [comment]
![grafik](https://github.com/Truly-Modular/Modular-Item-API/assets/67115074/ca224bd8-cbc7-4569-a467-e4d14c9e7656)
does this button not work?

**Comment by NJL5390** [comment]
Just chiming in to say that I was having this crash/disconnect issue but the latest version of the mod has fixed this for me.

Also to thank you for making this mod! I don't think I've been this excited for a mod release in quite some time so thank you for blessing us with this incredible mod!

**Comment by oinkratpig** [comment]
> ![grafik](https://user-images.githubusercontent.com/67115074/282289890-ca224bd8-cbc7-4569-a467-e4d14c9e7656.png) does this button not work?

Neither do

**Comment by Smartin-b** [comment]
you dont have Rougly enough items in by any chance, right?

**Comment by oinkratpig** [comment]
> you dont have Rougly enough items in by any chance, right? cause its known to have issues on servers and cause truly modular to not work on servers

I am using EMI, so that might be it. Is there a fix?

**Comment by Smartin-b** [comment]
sorry, i mean JER nor REI, i got confused by too many 3 letter acronyms, EMI seems to be fine

**Comment by Smartin-b** [comment]
So, i tried arround and im having trouble recreating this issue,did you try with the latest version of miapi (1.0.6)?

**Comment by oinkratpig** [comment]
Tried it again and it works now, for some reason. Thank you!
