### ISSUE TITLE
Server Crashes on startup with latest MiAPI

### ISSUE THREAD

**Issue by NJL5390** [Truly-Modular/Modular-Item-API#13]
**Describe the bug**
With the latest version of MiAPI (1.0.5), server will crash on startup when attempting to load this mod.

**To Reproduce**
1. Launch a  server with the latest MiAPI installed
2. Allow the server to run.
3. Server crashes and produces the below crash report

**Expected behavior**
The server loads normally and doesn't crash.

**Minecraft and Mod Version:**
Minecraft: 1.20.1
Forge/Fabric: Forge 47.2.5
Miapi: 1.0.5

**Additional context**
Crash Report: https://gist.github.com/NJL5390/f8406dd7191a9adfce6a1300cdf857cf

**Comment by Smartin-b** [comment]
should be fixed in miapi 1.0.6

**Comment by NJL5390** [comment]
Seems to be! Thanks a lot!
