### ISSUE TITLE
Items don't stack

### ISSUE THREAD

**Issue by bosszaza2547** [Truly-Modular/Modular-Item-API#16]
**Describe the bug**
when mine and pick up item that haven't been place it doesn't stack
like crafted oak plank or give some cobblestone then place and mine
then they don't stack

**To Reproduce**
1. give block that doesn't change on mine in creative mode
2. go survival mode place block
3. mine block
4. pick up block

Alternative
1.create survival world
2.mine wood for log
3.craft planks
4.place 1 plank
5.mine plank
6.pick up plank

**Expected behavior**
items stack

**Screenshots**
![image](https://github.com/Truly-Modular/Modular-Item-API/assets/107463319/1e611b66-e216-4373-b43e-7b054a2952b9)
![image](https://github.com/Truly-Modular/Modular-Item-API/assets/107463319/9a6e57da-0843-443d-93d1-42f6e1c806ae)

**Video**
https://github.com/Truly-Modular/Modular-Item-API/assets/107463319/0b2603b7-d673-46e2-8c6e-39775fdbc876
https://github.com/Truly-Modular/Modular-Item-API/assets/107463319/78bf1deb-b200-4b30-abb1-b2bf43e40896

**Minecraft and Mod Version:**
Minecraft:1.20.1
Forge/Fabric:architectury-9.1.12-forge, caelus-forge-3.1.0+1.20
Miapi:Truly-Modular-Archery-1.1-1.20.1-forge, Truly-Modular-Armory-1.3-1.20.1-forge, Truly-Modular-Arsenal-1.2-1.20.1-forge, Truly-Modular-miapi-forge-1.0.12-1.20.1
other:

**Additional context**
I think it has something to do with nbt tags
![image](https://github.com/Truly-Modular/Modular-Item-API/assets/107463319/00779b48-19b6-47fe-a289-d9cb53cf7c37)

**Comment by Smartin-b** [comment]
can you try if the issue perssists with these experimental jars?
https://cdn.discordapp.com/attachments/1098169086275489823/1183523107105935431/Truly-Modular-miapi-1.0.12-1.20.1-snapshot-fabric.jar?ex=6588a4c9&is=65762fc9&hm=798d7eb6bf30989f6b0e6c654a738f6977bcc0a81d21bcf9bbd1d9ccb00cfdb2&

https://cdn.discordapp.com/attachments/1098169086275489823/1183523107496017930/Truly-Modular-miapi-1.0.12-1.20.1-snapshot-forge.jar?ex=6588a4c9&is=65762fc9&hm=a3e82361c4b89aa80b7f3648374f0057fe69d8eb99c4808d3276f3044c47f029&

**Comment by bosszaza2547** [comment]
> can you try if the issue perssists with these experimental jars? https://cdn.discordapp.com/attachments/1098169086275489823/1183523107105935431/Truly-Modular-miapi-1.0.12-1.20.1-snapshot-fabric.jar?ex=6588a4c9&is=65762fc9&hm=798d7eb6bf30989f6b0e6c654a738f6977bcc0a81d21bcf9bbd1d9ccb00cfdb2&
> 
> https://cdn.discordapp.com/attachments/1098169086275489823/1183523107496017930/Truly-Modular-miapi-1.0.12-1.20.1-snapshot-forge.jar?ex=6588a4c9&is=65762fc9&hm=a3e82361c4b89aa80b7f3648374f0057fe69d8eb99c4808d3276f3044c47f029&

yeah it works, that was quick
