### ISSUE TITLE
Crash when modifying BetterNether items

### ISSUE THREAD

**Issue by JDLENL** [Truly-Modular/Modular-Item-API#18]
**Describe the bug**
Game crashes when trying to render info for BetterNether tools.

**To Reproduce**
Install this mod and BetterNether and attempt to modify a tool from the mod.

**Expected behavior**
Tool should not crash the game, and should either be ignored by the table or compatible with it.

**Crash Log:**
https://mclo.gs/VLWdzdR

**Comment by Smartin-b** [comment]
the issue seems to be an outdated version of arsenal.
try updating arsenal to 1.3.

**Comment by JDLENL** [comment]
Edit: just got a crash modifying a vanilla diamond sword. What gives?
https://mclo.gs/0C9mj4j

**Comment by Smartin-b** [comment]
Sth about the internal module logic was changed, breaking all guards from Arsenal except the vanilla guard.
Using those guards and replacing them or the balde in them will result in a crash. They propably dont render correctly either. Updating Arsenal should fix this

**Comment by JDLENL** [comment]
> the issue seems to be an outdated version of arsenal. try updating arsenal to 1.3.
> 
> Miapi 1.1.0 is nolonger compatible with arsenal 1.2 and older. Archery and Armory did not need to be updated for miapi 1.1.0, but arsenal used sth that was deprecated with miapi 1.1.0

There is no 1.3 arsenal visible on curseforge.
![image](https://github.com/Truly-Modular/Modular-Item-API/assets/29065768/660c75d3-8db7-43ef-80d8-1e840b40fc23)

**Comment by Smartin-b** [comment]
i hate curseforge... while i upload the file and figure out why my auto upload failed this time again,
https://modrinth.com/mod/truly-modular-arsenal/version/Arsenal-1.3-1.20.1-fabric
the jar is up on modrinth

i am aware cfs description isnt formated correctly, tell Curseforge to fix their website and properly support markdown formatting

**Comment by JDLENL** [comment]
lol yeah it's a hassle sometimes. I've updated to 1.3 from modrinth, thank you.

**Comment by Smartin-b** [comment]
if you are wondering the description is straight copied from modrinth and both cf and modrinth are set to markdown formating. just cursefore is too stupid todo ir right...

**Comment by Smartin-b** [comment]
so, jar is uploaded and aproved on cf now https://legacy.curseforge.com/minecraft/mc-mods/truly-modular-arsenal/files/4968195
im gonna asume issue is resolved now, so im gonna close this issue
