### ISSUE TITLE
Modular Stuff doesn't show up as model (Armor, Weapons etc.)

### ISSUE THREAD

**Issue by MewoMewoMewo** [Truly-Modular/Modular-Item-API#19]
**I use modular armor or weapons and it is invisible**
Ye IDK why. Other mods maybe?

**To Reproduce**
1. no clue

**Expected behavior**
That it shows up as a model, duh.

**Screenshots**
https://i.imgur.com/O3ChtBi.png

**Minecraft and Mod Version:**
Minecraft:
Fab:
1.20.1, newest mod version

**Comment by Smartin-b** [comment]
can you send me the logs and the full mod list?

**Comment by MewoMewoMewo** [comment]
> can you send me the logs and the full mod list?

What Logs?

And...sure
With LIBs?

**Comment by Smartin-b** [comment]
with libs yes, a screenshot of your loader works as well, logs can be found in your mc folder logs latest.log

**Comment by MewoMewoMewo** [comment]
> with libs yes, a screenshot of your loader works as well, logs can be found in your mc folder logs latest.log

Loader? So Launcher? f.e. Badlion?

**Comment by Smartin-b** [comment]
does your loader not provide any overview? well, eh, a screenshot of the mods folder should do

**Comment by MewoMewoMewo** [comment]
![Uploading Screenshot 2023-12-20 224507.jpg…]()

**Comment by MewoMewoMewo** [comment]
![Screenshot 2023-12-20 224538](https://github.com/Truly-Modular/Modular-Item-API/assets/154471251/52964180-946e-432e-8a34-e89808bdf16f)
![Screenshot 2023-12-20 224556](https://github.com/Truly-Modular/Modular-Item-API/assets/154471251/4eda403f-c364-4ad8-bb6d-c537a91d5569)
![Screenshot 2023-12-20 224621](https://github.com/Truly-Modular/Modular-Item-API/assets/154471251/0b235fc3-37d6-4fd2-92c7-20daf6627465)
![Screenshot 2023-12-20 224645](https://github.com/Truly-Modular/Modular-Item-API/assets/154471251/b7a02756-6c58-4551-a328-50f116927185)
![Screenshot 2023-12-20 224658](https://github.com/Truly-Modular/Modular-Item-API/assets/154471251/d402ef90-ac40-4bcc-9bd9-18c4bf63710b)
![Screenshot 2023-12-20 224710](https://github.com/Truly-Modular/Modular-Item-API/assets/154471251/8bc1a161-79d0-413d-8bb1-2e53de1884d8)

**Comment by MewoMewoMewo** [comment]
![Screenshot 2023-12-20 224507](https://github.com/Truly-Modular/Modular-Item-API/assets/154471251/6131596d-986d-42a9-bc45-a5ea8c113213)

**Comment by MewoMewoMewo** [comment]
[latest.zip](https://github.com/Truly-Modular/Modular-Item-API/files/13732908/latest.zip)

**Comment by MewoMewoMewo** [comment]
@Smartin-b there ya go

**Comment by MewoMewoMewo** [comment]
hello? Smartin?

**Comment by Smartin-b** [comment]
yeye, one second, testing over 100 mods isnt that fast^^

**Comment by Smartin-b** [comment]
Entity Texture features breaks our rendering.
i will investigate this further, but that will take time

**Comment by MewoMewoMewo** [comment]
> Entity Texture features breaks our rendering. i will investigate this further, but that will take time

alrighty
I will disable that

**Comment by Smartin-b** [comment]
![grafik](https://github.com/Truly-Modular/Modular-Item-API/assets/67115074/4d38237b-3af5-48ca-ad28-afecf0faff8c)
enabling this and also re-entering the world works as well.

**Comment by Smartin-b** [comment]
this can be found here if you go to your ingame modlist
![grafik](https://github.com/Truly-Modular/Modular-Item-API/assets/67115074/4f8e5526-1ac5-4a83-afac-e4f3016b9681)

**Comment by MewoMewoMewo** [comment]
Thx

**Comment by Smartin-b** [comment]
Entity Texture Features is now compatible without fallback renderer in the neweset miapi release
