### ISSUE TITLE
Longbow is completely invisible.

### ISSUE THREAD

**Issue by CyaniideDrive** [Truly-Modular/Modular-Item-API#20]
**Describe the bug**
When creating a longbow with a precision rest (copper arms, iron rest) the model is completely invisible with Better Combat.

**To Reproduce**
1. Create a longbow.
2.Hold it. 

**Expected behavior**
The longbow should be visible.

**Screenshots**
With Better Combat.
![image](https://github.com/Truly-Modular/Modular-Item-API/assets/2701541/771a757b-fe0c-4ea3-aa4c-8bdb203ecb3f)

Without Better Combat.
![image](https://github.com/Truly-Modular/Modular-Item-API/assets/2701541/c6950b4c-10ef-4ec3-83a9-ddc191b85dc0)

**Minecraft and Mod Version:**
Minecraft:
Forge: 47.2.17
Miapi: 1.1.1
Archery: 1.1
Arsenal: 1.3
Armory: 1.3
Better Combat: 1.8.1

**Full Mod List**
This one is big, but here ya go.
[1.20.1-forge]-Epic-Knights-8.11.jar
3dskinlayers-forge-1.5.4-mc1.20.1.jar
ad_astra-forge-1.20.1-1.15.5.jar
ae2wtlib-15.2.1-forge.jar
aether-1.20.1-1.0.0-beta.2.2-neoforge.jar
alexscaves-1.0.9.jar
alexsmobs-1.22.7.jar
AmbientSounds_FORGE_v5.3.5_mc1.20.1.jar
Apotheosis-1.20.1-7.2.0.jar
ApothicAttributes-1.20.1-1.2.1.jar
appleskin-forge-mc1.20.1-2.5.1.jar
appliedenergistics2-forge-15.0.15.jar
architectury-9.1.12-forge.jar
ars_creo-1.20.1-4.0.1.jar
ars_elemental-1.20.1-0.6.3.2.jar
ars_nouveau-1.20.1-4.8.2-all.jar
ars_ocultas-1.20.1-1.1.0-all.jar
artifacts-forge-9.2.0.jar
AttributeFix-Forge-1.20.1-21.0.4.jar
azurelib-neo-1.20.1-2.0.17.jar
balm-forge-1.20.1-7.2.1.jar
BetterAdvancements-1.20.1-0.3.2.161.jar
betterarcheology-1.1.0.jar
bettercombat-forge-1.8.1+1.20.1.jar
BetterCompatibilityChecker-forge-4.0.8+mc1.20.1.jar
BetterThirdPerson-Forge-1.20-1.9.0.jar
BiomesOPlenty-1.20.1-18.0.0.592.jar
Bookshelf-Forge-1.20.1-20.1.7.jar
Botania-1.20.1-441-FORGE.jar
BotanyPots-Forge-1.20.1-13.0.18.jar
BotanyTrees-Forge-1.20.1-9.0.7.jar
botarium-forge-1.20.1-2.2.1.jar
Bountiful-6.0.3+1.20.1-forge.jar
buildinggadgets2-1.0.6.jar
bygonenether-1.3.2-1.20.x.jar
caelus-forge-3.1.0+1.20.jar
"catacalysm delight 1.20.1 - 0.1.1.jar"
cataclysmiccombat-1.2.jar.disabled
cc-tweaked-1.20.1-forge-1.108.4.jar
charmofundying-forge-6.4.5+1.20.1.jar
chefs-delight-1.0.3-forge-1.20.1.jar
chunksending-1.20.1-2.8.jar
citadel-2.4.9-1.20.1.jar
cloth-config-11.1.106-forge.jar
Clumps-forge-1.20.1-12.0.0.3.jar
collective-1.20.1-7.23.jar
comforts-forge-6.3.4+1.20.1.jar
connectedglass-1.1.10-forge-mc1.20.1.jar
connectivity-1.20.1-4.9.jar
Controlling-forge-1.20.1-12.0.2.jar
corpse-1.20.1-1.0.9.jar
cosmeticarmorreworked-1.20.1-v1a.jar
CrabbersDelight-1.20.1-1.1.3a.jar
crafting-on-a-stick-1.20.1-1.1.4.jar
craftingtweaks-forge-1.20-18.2.2.jar
create_enchantment_industry-1.20.1-for-create-0.5.1.f-1.2.7.h.jar
"create_misc_and_things_ 1.20.1_4.0A.jar"
create_recycle_1.0.2_forge_1.20.1.jar
create-1.20.1-0.5.1.f.jar
createaddition-1.20.1-1.2.1.jar
create-confectionery1.20.1_v1.1.0.jar
create-new-age-forge-1.20.1-1.1.jar
createoreexcavation-1.20-1.4.2.jar
create-stuff-additions1.20.1_v2.0.4a.jar
CreativeCore_FORGE_v2.11.14_mc1.20.1.jar
creeperoverhaul-3.0.1-forge.jar
Cucumber-1.20.1-7.0.6.jar
cuisinedelight-1.1.11.jar
cupboard-1.20.1-2.1.jar
curios-forge-5.4.6+1.20.1.jar
curiotiab-1.20.1-2.0.2.jar
curious_armor_stands-1.20-5.0.1.jar
Cyclic-1.20.1-1.12.4.jar
DarkUtilities-Forge-1.20.1-17.0.3.jar
"Dungeon Crawl-1.20.1-2.3.14.jar"
DungeonsArise-1.20.1-2.1.57-release.jar
easy_piglins-1.20.1-1.0.1.jar
easy_villagers-1.20.1-1.0.17.jar
EasyAnvils-v8.0.1-1.20.1-Forge.jar
elevatorid-1.20.1-lex-1.9.jar
elytraslot-forge-6.3.0+1.20.1.jar
embeddium-0.2.13+mc1.20.1.jar
embeddiumplus-1.20.1-v1.1.0.jar
EnchantmentDescriptions-Forge-1.20.1-17.0.9.jar
EnderIO-1.20.1-6.0.23-alpha.jar
"EndlessBiomes 1.4.2s - 1.20.1.jar"
ends_delight-1.20.1-1.0.1.jar
entangled-1.3.16-forge-mc1.20.jar
epicsamurai-0.0.32-1.20.1-neo.jar.disabled
evenmoreinstruments-1.20+1.20.1-3.0.jar
explorify-v1.3.0-mc1.20.jar
Fallingleaves-1.20.1-2.1.0.jar
FarmersDelight-1.20.1-1.2.3.jar
farmingforblockheads-forge-1.20.1-14.0.2.jar
farsight-1.20.1-3.6.jar
FastFurnace-1.20.1-8.0.1.jar
FastLeafDecay-31.jar
FastSuite-1.20.1-5.0.1.jar
FastWorkbench-1.20.1-8.0.2.jar
ferritecore-6.0.1-forge.jar
findme-3.1.1-forge.jar
firstperson-forge-2.2.4-mc1.20.1.jar
flib-1.20.1-0.0.11.jar
FluxNetworks-1.20.1-7.2.0.14.jar
framework-forge-1.20.1-0.6.16.jar
ftbbackups2-forge-1.20-1.0.23.jar
ftb-chunks-forge-2001.2.4.jar
ftb-essentials-forge-2001.2.2.jar
ftb-library-forge-2001.1.4.jar
ftb-quests-forge-2001.2.1.jar
ftb-teams-forge-2001.1.4.jar
ftb-ultimine-forge-2001.1.2.jar
fusion-1.1.0b-forge-mc1.20.1.jar
geckolib-forge-1.20.1-4.3.1.jar
genshinstrument-1.20+1.20.1-3.4.jar
geophilic-v2.1.0-mc1.20u1.20.2.jar
GeOre-1.20.1-2.4.2.jar
goblintraders-forge-1.20.1-1.9.3.jar
immersive_aircraft-0.6.2+1.20.1-forge.jar
interiors-0.5.2+mc1.20.1-FORGE.jar
ironchest-1.20.1-14.4.4.jar
ironfurnaces-1.20.1-4.1.3.jar
IronJetpacks-1.20.1-7.0.2.jar
Irons_Recipe_Additions_1.20.1_modversion_1.3.jar
irons_spellbooks-1.20.1-2.1-20231218.052604-6.jar
item-filters-forge-2001.1.0-build.59.jar
ItemProductionLib-1.20.1-1.0.0a-all.jar
Jade-1.20.1-forge-11.6.3.jar
jei-1.20.1-forge-15.2.0.27.jar
jmi-forge-1.20.1-0.14-45.jar
journeymap-1.20.1-5.9.18-forge.jar
JustEnoughResources-1.20.1-1.4.0.238.jar
Kambrik-6.1.1+1.20.1-forge.jar
kleeslabs-forge-1.20-15.0.0.jar
kotlinforforge-4.9.0-all.jar
"L_Enders_Cataclysm-1.84 -1.20.1.jar"
lootr-1.20-0.7.30.73.jar
macawsbridgesbop-1.20-1.1.jar
macawsroofsbop-1.20-1.0.jar
majrusz-library-forge-1.20.1-7.0.2.jar
majruszs-accessories-forge-1.20.1-1.4.0.jar
majruszs-enchantments-forge-1.20.1-1.10.5.jar
MaxHealthFix-Forge-1.20.1-12.0.2.jar
mcw-bridges-2.1.1-mc1.20.1forge.jar
mcw-doors-1.1.0forge-mc1.20.1.jar
mcw-fences-1.0.7-mc1.20.1forge.jar
mcwfencesbop-1.20-1.0.jar
mcw-furniture-3.2.1-mc1.20.1forge.jar
mcwfurnituresbop-1.20-1.1.jar
mcw-lights-1.0.6-mc1.20.1forge.jar
mcw-paintings-1.0.5-1.20.1forge.jar
mcw-paths-1.0.3forge-mc1.20.1.jar
mcw-roofs-2.2.4b-mc1.20.1forge.jar
mcw-trapdoors-1.1.2-mc1.20.1forge.jar
mcw-windows-2.2.1-mc1.20.1forge.jar
Mekanism-1.20.1-10.4.5.19.jar
MekanismTools-1.20.1-10.4.5.19.jar
miners_delight-1.20.1-1.2.1.jar
modelfix-1.14.jar
modernfix-forge-5.10.1+mc1.20.1.jar
modonomicon-1.20.1-forge-1.42.0.jar
moonlight-1.20-2.8.67-forge.jar
MouseTweaks-forge-mc1.20-2.25.jar
mutil-1.20.1-6.1.1.jar
MysticalAgradditions-1.20.1-7.0.2.jar
MysticalAgriculture-1.20.1-7.0.7.jar
mysticaloaktree-1.20-1.11.jar
NaturesCompass-1.20.1-1.11.2-forge.jar
netherportalfix-forge-1.20-13.0.1.jar
nethersdelight-1.20.1-4.0.jar
NoChatReports-FORGE-1.20.1-v2.2.2.jar
notenoughanimations-forge-1.6.4-mc1.20.jar
occultism-1.20.1-1.95.1.jar
oceansdelight-1.0.2-1.20.jar
octolib-0.1.jar
oculus-mc1.20.1-1.6.13.jar
Paraglider-forge-20.1.2.jar
PassiveSkillTree-1.20.1-BETA-0.6.3a-all.jar
Patchouli-1.20.1-84-FORGE.jar
PickleTweaks-1.20.1-8.0.1.jar
PigPen-Forge-1.20.1-15.0.2.jar
Placebo-1.20.1-8.6.0.jar
player-animation-lib-forge-1.0.2-rc1+1.20.jar
polyeng-forge-0.1.0-1.20.1.jar
polylib-forge-2000.0.3-build.97.jar
polymorph-forge-0.49.2+1.20.1.jar
Powah-5.0.4.jar
"ProjectE Integration-1.20.1-7.1.0.jar"
ProjectE-1.20.1-PE1.0.1.jar
ProjectExpansion-1.20.1-1.0.0.jar
ProjectExtended-1.20.1-1.5.0.jar
projectvibrantjourneys-1.20.1-6.0.0.jar
PuzzlesLib-v8.1.11-1.20.1-Forge.jar
ramcompat-1.20.1-0.1.0.2.jar
relics-1.20.1-0.5.2.1.jar
reliquary-1.20.1-2.0.36.1199.jar
repurposed_structures-7.1.11+1.20.1-forge.jar
resourcefulconfig-forge-1.20.1-2.1.0.jar
resourcefullib-forge-1.20.1-2.1.19.jar
Runelic-Forge-1.20.1-18.0.2.jar
Searchables-forge-1.20.1-1.0.2.jar
Shrink-1.20.1-1.4.5.jar
SilentCompat-forge-1.20.1-1.3.5.jar
silent-gear-1.20.1-3.5.2.jar
silent-lib-1.20.1-8.0.0.jar
silents-gems-1.20.1-4.6.0.jar
SimpleStorageNetwork-1.20.1-1.10.0.jar
simplyswords-forge-1.51.5-1.20.1.jar.disabled
SkyVillages-1.0.3-1.19.2-1.20.x-forge-release.jar
sliceanddice-forge-3.2.0.jar
smallernetherportals-1.20.1-3.6.jar
SmartBrainLib-forge-1.20.1-1.12.jar
solapplepie-1.20.1-2.3.0.jar
sophisticatedbackpacks-1.20.1-3.19.4.978.jar
sophisticatedcore-1.20.1-0.5.111.517.jar
sophisticatedstorage-1.20.1-0.8.62.671.jar
storagedrawers-1.20.1-12.0.2.jar
structureessentials-1.20.1-3.2.jar
supermartijn642configlib-1.1.8-forge-mc1.20.jar
supermartijn642corelib-1.1.16-forge-mc1.20.1.jar
supplementaries-1.20-2.7.12.jar
sushigocrafting-1.20.1-0.4.3.jar
teamprojecte-1.20.1-1.1.2.jar
TerraBlender-forge-1.20.1-3.0.0.169.jar
tetra-1.20.1-6.0.0-pre.0.jar
textrues_embeddium_options-0.1.3+mc1.20.1.jar
The_Undergarden-1.20.1-0.8.9.jar
time-in-a-bottle-4.0.4-mc1.20.1.jar
titanium-1.20.1-3.8.24.jar
ToastControl-1.20.1-8.0.3.jar
ToolBelt-1.20-1.20.0.jar
torchmaster-20.1.5.jar
TradingPost-v8.0.1-1.20.1-Forge.jar
Truly-Modular-Archery-1.1-1.20.1-forge.jar
Truly-Modular-Armory-1.3-1.20.1-forge.jar
Truly-Modular-Arsenal-1.3-1.20.1-forge.jar
Truly-Modular-miapi-forge-1.1.1-1.20.1.jar
twilightdelight-2.0.3.jar
twilightforest-1.20.1-4.3.1893-universal.jar
voicechat-forge-1.20.1-2.4.32.jar
waystones-forge-1.20-14.1.3.jar
WitherSkeletonTweaks-1.20.1-9.0.1.jar
wormhole-1.1.15-forge-mc1.20.jar
YungsApi-1.20-Forge-4.0.2.jar
YungsBetterDesertTemples-1.20-Forge-3.0.3.jar
YungsBetterDungeons-1.20-Forge-4.0.3.jar
YungsBetterEndIsland-1.20-Forge-2.0.4.jar
YungsBetterJungleTemples-1.20-Forge-2.0.4.jar
YungsBetterMineshafts-1.20-Forge-4.0.4.jar
YungsBetterNetherFortresses-1.20-Forge-2.0.5.jar
YungsBetterOceanMonuments-1.20-Forge-3.0.4.jar
YungsBetterStrongholds-1.20-Forge-4.0.3.jar
YungsBetterWitchHuts-1.20-Forge-3.0.3.jar
YungsBridges-1.20-Forge-4.0.3.jar
YungsExtras-1.20-Forge-4.0.3.jar

**Comment by CyaniideDrive** [comment]
It's definitely Better Combat, since you can see it with it, and only it, removed, but I thought the mod had full support for Better Combat.

**Comment by CyaniideDrive** [comment]
The oddest thing is that tools and even custom swords work fine.
![image](https://github.com/Truly-Modular/Modular-Item-API/assets/2701541/0c1d2f51-fe1a-474f-a9df-5cd22594361a)

**Comment by CyaniideDrive** [comment]
I'm so confused, somehow after making the sword to test, the bow is visible now too :/
![image](https://github.com/Truly-Modular/Modular-Item-API/assets/2701541/d2541db8-aca5-4ea8-98db-6e0ba9b8c049)
How does something like this even happen?

**Comment by CyaniideDrive** [comment]
OK, I've figured out the cause.
I turned off shaders when I realized that they aren't supported, and turning off shaders doesn't make things visible again, they stay as invisible as when the shaders are on.

**Comment by Smartin-b** [comment]
yes, shaders are partially supported, in miapi.json you can see a forcefallbackrenderer, if oyu set this to true, shaders are supported, but all modular items will look significantly worse.
are you using optifine for shaders? with iris or iris derivatives this should be auto on.

**Comment by Smartin-b** [comment]
turning off shaders alone also doesnt fix a lot. once shaders got enabled truly modulars default rendering is broken and wont work anymore until you restarted the game. i do recommend simply removing oculus quite honestly

**Comment by Smartin-b** [comment]
if the issue is only related to shader compat feel free to close the issue

**Comment by CyaniideDrive** [comment]
It was Oculus (a derivative), and I managed to find the fallback renderer, it's still a bit spotty with rendering stuff though, like arrows missing their fletching and similat small issues.

It's great the option is there though.

**Comment by Smartin-b** [comment]
that sounds very odd, first time im hearing about any issues with the fallback renderer.
did you restart the game after you enabled it?

**Comment by Smartin-b** [comment]
@CyaniideDrive does this still happen in the latest release?

**Comment by Smartin-b** [comment]
Cannot reproduce this issue locally, if no further information is provided i will close this issue on the Januarry 6th

**Comment by Smartin-b** [comment]
eh, forgot to close this, im asuming the new alt renderer fixes this problems either way
