### ISSUE TITLE
Crashes on server with immersive engineering

### ISSUE THREAD

**Issue by Rosenblack** [Truly-Modular/Modular-Item-API#21]
**Describe the Issue**
Just as the title says, doesnt even fully start up before it crashes

**The other mod/mods in Question**
Seems just immersive engineering

**Expected behavior**
to not crash
[crash-2023-12-25_05.08.17-server.txt](https://github.com/Truly-Modular/Modular-Item-API/files/13765547/crash-2023-12-25_05.08.17-server.txt)

**Comment by Smartin-b** [comment]
should be fixed in the newest release https://modrinth.com/mod/modular-item-api/version/1.1.4-1.20.1
Curseforge should aprove it in a bit as well
