### ISSUE TITLE
Incompatibility with Moonlight Lib

### ISSUE THREAD

**Issue by Nathanator9000** [Truly-Modular/Modular-Item-API#22]
Description: Minecraft crashes when playing with MIAPI and Moonlight Lib

Mod Conflict: MIAPI 1.1.5, Architectury 9.1.12, and Moonlight 2.8.78 (Forge Modloader)

Expected Behavior: Game should complete loading.

[crash-2023-12-29_13.48.44-client.txt](https://github.com/Truly-Modular/Modular-Item-API/files/13795570/crash-2023-12-29_13.48.44-client.txt)

[latest.log](https://github.com/Truly-Modular/Modular-Item-API/files/13795574/latest.log)

![Capture](https://github.com/Truly-Modular/Modular-Item-API/assets/149219168/236a8c02-000a-47e5-89d5-3e740a5e4177)

Here I have attached the crash report, launch log, and a picture of the error message it provides.

**Comment by Nathanator9000** [comment]
I apologize for that. My modpack was crashing and I tried to isolate it and missed that dependency. I finally have isolated it, but it involves multiple mods. 

My game crashes if I have miapi, moonlight, and combat next on at the same time. MIAPI seems to work fine when paired with only moonlight or only combat next, but crashes when both are in the same modpack. Moonlight and combat next can launch together as long as miapi is not installed. It does not generate a crash report, all I have is a launcher log that I copied from the game output. Sorry for the mistake on the first part.

[Launcher Log.txt](https://github.com/Truly-Modular/Modular-Item-API/files/13795959/Launcher.Log.txt)

**Comment by Nathanator9000** [comment]
I apologize for the mistake on the first post. I was working on my modpack and notice it was crashing and tried to isolate it. Unfortunately it seems to be multiple mods together that cause this crash. All these mods work together unless combined at the same time. (I do also have the dependencies, architectury and caelus)

Mod List: Let's Do Api 1.2.8, Combat next 1.0.2, Moonlight 2.8.78, Caelus 3.1.0, Architectury 9.1.12, MIAPI 1.1.5 

This is an updated version of my previous comment because I left out Let's Do API on accident.

**Comment by Smartin-b** [comment]
try running it on forge 47.1.3.
It is the last forge version that works with Neoforge and MinecraftForge mods so miapi (and other mods) are currently built for this version of forge.

**Comment by Nathanator9000** [comment]
Thank you for the suggestion, but it still causes the same crash unfortunately. This error still appears in the log.

Caused by: java.lang.ClassNotFoundException: com.llamalad7.mixinextras.MixinExtrasBootstrap
21:45:52.028
game
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
21:45:52.028
game
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
21:45:52.028
game
at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137)
21:45:52.028
game
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
21:45:52.028
game
at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137)
21:45:52.028
game
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)

**Comment by Smartin-b** [comment]
after a bit of investigation it seems Combat next is at fault. It ships a broken version of MixinExtras.
When another mod ships a functional version and forge chooses the Functional version, the game starts.
If it doesnt, your game crashes. So any mod using MixinExtras Miapi(Nucleus), DoItApi or Moonlight change the outcome of what MixinExtras version forge chooses.

**Comment by Smartin-b** [comment]
Panda submitted a fix https://github.com/Thelnfamous1/Combat-Next/pull/12
you can download the fix here if you want: https://cdn.discordapp.com/attachments/1096639281675632640/1190501436300201994/combat_next-1.20.1-1.0.2-all.jar?ex=65a207dc&is=658f92dc&hm=4e8752cdaf397ec44d67f82dc9cdf9a5506ae0d4f9fc5587ea480f71c7ffeff6&

But we dont recommend playing with miapi and Combat next, since most of Combat nexts changes dont affect modular weapons and their balancing, so they probably will feel out of place
