### ISSUE TITLE
[Feature Request] Modify BetterCombat attack range attribute with different blades and handle

### ISSUE THREAD

**Issue by NeuTraLZero** [Truly-Modular/Modular-Item-API#23]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Give different handles and blades on a modular weapon different attack range values for BetterCombat

**Describe alternatives you've considered**
If only the blade modifies the range, it would be fine.

**Additional context**
Currently something like a Katana or a Broadsword will only reach up to 2.5 blocks like a regular sword, I think it would be cool if they could attack a bit further

**Comment by Smartin-b** [comment]
At the moment handles do affect attackrange, i could add sth to extend attackrange with bc on certain configurations

**Comment by Smartin-b** [comment]
will change the logic in the next update to reflect a mixture between miapis attackrange and BCs suggestion

**Comment by Smartin-b** [comment]
somewhat added in latest release, im now using a mixture between BCs suggested and Truly Modulars set attackrange
