### ISSUE TITLE
Add the option to put armor trims onto modular armors.

### ISSUE THREAD

**Issue by LucioMagno** [Truly-Modular/Modular-Item-API#24]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

Support to adding Armor Trims to modular armors.

**Comment by Smartin-b** [comment]
we will look into it, but its not that simple with modular items

**Comment by Smartin-b** [comment]
added in latest release

**Comment by LucioMagno** [comment]
Amazing! Great job <3
