### ISSUE TITLE
Buff Armor points given by Heavy Armor modules!

### ISSUE THREAD

**Issue by LucioMagno** [Truly-Modular/Modular-Item-API#25]
**Is your feature request related to a problem? Please describe.**
Yes, the downsides of wearing heavy armor heavily outweigh (pun intended) the upsides!

**Describe the solution you'd like**
increase either armor toughness or armor points given by heavy armor by a hefty ammount, maybe 30 to 40% more armor than their normal armor counterpart, because the downsides, specially the food drain makes it totally not worth it to wear them given how little the armor bonus is at the moment.

**Describe alternatives you've considered**
Reducing the penalties is an option, although i think they should remain as they give the heavy armor its personality.

**Additional context**
Currently, the additional armor granted for a diamond helmet is only .3 which is very little, i believe it should be at least 1 entire point, maybe 1.2!

**Comment by Smartin-b** [comment]
the main reason why it is so low is behind how vanilla does armor calculations, its incredible stupid.
https://www.curseforge.com/minecraft/mc-mods/armor-curve
if you are interested how stupid the armor points apply.
i think ill buff heavy armor soon, but it wont be with raw armor points

**Comment by LucioMagno** [comment]
Interesting! I hope you find a cool way around this nonsense.

**Comment by Smartin-b** [comment]
so, should be done in the lateset release, took a while longer than expected todo lol
