### ISSUE TITLE
Server crash - with mohist + other mods

### ISSUE THREAD

**Issue by BBoldt** [Truly-Modular/Modular-Item-API#26]
**Describe the bug**
Server crashes during startup.

**Expected behavior**
Expected server to start.

**Screenshots**
n/a

**Minecraft and Mod Version:**
Minecraft: 1.20.1
Forge/Fabric: Forge 47.2.20
Miapi: 1.1.8
other: using bukkitforge implementation, mohist-1.20.1-521-server
https://mohistmc.com/

**Full Mod List**
https://gist.github.com/BBoldt/5863813edf7d37eaf44df270a72a9b26

**Ingame Logs**
https://gist.github.com/BBoldt/2ae9be7980a62d81a3a053dce7062836
**Additional context**
I'm not sure whether this is an issue with the type of server I'm using or a mod conflict. Truly Modular works fine in Singleplayer with all the other mods. The server starts normally without Truly Modular.

**Comment by Smartin-b** [comment]
it seems to be a mixin conflict, i disabled the conflicting mixin here, im looking for a better solution but this should work for now
https://cdn.discordapp.com/attachments/1098169086275489823/1199088677796720721/Truly-Modular-miapi-1.1.8-1.20.1-snapshot-forge.jar?ex=65c1455a&is=65aed05a&hm=a3dd0e54201e729ebe59fbcd9bd4d9a176ecdd8a27adc8dac0acfdc1183384f0&

**Comment by BBoldt** [comment]
So that worked!

Here is my new log, server booted:
https://gist.github.com/BBoldt/a3701dda42f1be07ec5ecb71b12d8ded

some miapi stuff is in the log near the end

**Comment by Smartin-b** [comment]
eh, thats mostly because forge servers are very scuffed

**Comment by Smartin-b** [comment]
was fixed in last release
