### ISSUE TITLE
Truly Modular - Siny tra Conn ector Incompatibility

### ISSUE THREAD

**Issue by Popsikul** [Truly-Modular/Modular-Item-API#27]
### Mod Name

Siny tra Conn ector

### Mod Homepage

https://modrinth.com/mod/connector

### Minecraft version

1.20.1

### Describe the bug

When using the mods together, modular tools will lack attributes/stats and become ineffective

### Steps to reproduce

1. Download Truly Modular and its modules/dependencies.
2. Download Sinytra connector (as well as connector extras and forgified fabric API) to the same modpack
3. Load up the game and modify a tool in the modular workbench

### Logs

https://gist.github.com/Popsikul/473586f68c8e502e15efeb9bfe15af70

**Comment by This1Potato** [comment]
Was this with Fabric Truly Modular or Forge Truly Modular?

**Comment by Smartin-b** [comment]
Hm, very weird. This should fix the issue, can you confirm that it does?
https://cdn.discordapp.com/attachments/1098169086275489823/1200213096497676328/Truly-Modular-miapi-1.1.9-1.20.1-snapshot-forge.jar?ex=65c55c8d&is=65b2e78d&hm=cbe76a1d6481e119660f30743a5adbebe834225c44bdcac767e2fd792ca260df&

**Comment by Popsikul** [comment]
Forge.

**Comment by Popsikul** [comment]
I tried this JAR, but it hasn't changed the issue

**Comment by Smartin-b** [comment]
Weird, it did for me, are you sure u removed the old miapi jar?

**Comment by Popsikul** [comment]
I tried it in a new modpack (with just the two mods and their
dependencies/companions) and i was able to make it work! Something still
appears to be causing the issue in the modpack I'm trying to set up though,
so i will try and share an update on that.

**Comment by Popsikul** [comment]
Thank you for the assistance!

**Comment by Popsikul** [comment]
Ignore my previous emails, it works perfectly! Thank you again for your help

**Comment by Smartin-b** [comment]
fixed in latest release
