### ISSUE TITLE
Material repair ingredients have their matching stacks accessed before tag reload, bricking them.

### ISSUE THREAD

**Issue by sisby-folk** [Truly-Modular/Modular-Item-API#29]
`Ingredient` caches the result of `getMatchingStacks()` when it's called, and it's possible to call the method _before_ tags are actually loaded - this causes `Ingredient` to permanently contain the incorrect list of stacks from before the tag was actually loaded, breaking its usage in recipes.

miapi does this in [MaterialProperty.java#L98-L108](https://github.com/Truly-Modular/Modular-Item-API/blob/main/common/src/main/java/smartin/miapi/modules/material/MaterialProperty.java#L98-L108) with several calls to getMatchingStacks(), and truly modular armory calls `test()` [GenerateArmorModularConverter.java#L43](https://github.com/Truly-Modular/Armory/blob/master/common/src/main/java/smartin/armory/GenerateArmorModularConverter.java#L43) in the same place via `assignStats`. 

This is presumably because `MiapiReloadListener` is running *before* `TagManagerLoader` - when it needs to run after. If architectury allows you to set a dependency on the tag reloader, go ahead and do so.

The result is that the repair ingredient for wooden and stone tools becomes completely empty, preventing them from being repaired at an anvil.

We caught this because our own mod (Tinkerer's Smithing) has a mixin designed to prevent it from happening - here's a nice log of that happening for more detail and a stack trace: https://mclo.gs/NRksw99

**Comment by sisby-folk** [comment]
Here's a screenshot of a wooden pickaxe being non repairable when this mod is installed.

![image](https://github.com/Truly-Modular/Modular-Item-API/assets/55819817/eb975dca-a0c8-482d-b2cf-7affe167e072)

**Comment by Smartin-b** [comment]
huh? thats weird, reading a tag does brick it?
well anyways guess ill just delay truly modulars reload logic until after the tags are setup

**Comment by sisby-folk** [comment]
You can look at the logic of `Ingredient.getMatchingStacks()` yourself - here's a screenshot
![image](https://github.com/Truly-Modular/Modular-Item-API/assets/55819817/99a2ccd4-d8dc-422c-ac32-9a43a789adc7)

**Comment by Smartin-b** [comment]
cool, ig i should just mixin into minecrafts reload logic and trigger after the initial loading is through to start miapis logic

**Comment by sisby-folk** [comment]
in fabric you have `IdentifiableResourceReloadListener` that handles this:

![image](https://github.com/Truly-Modular/Modular-Item-API/assets/55819817/be2cfa0b-d52d-4fae-8fc4-2add22c37ba7)

not sure what you have access to for forge.

**Comment by Smartin-b** [comment]
actually the architectury implementation supports dependencies, so ig ill use that

**Comment by Smartin-b** [comment]
So, hey, i tried architecturies implementation and while it seems to work ( i checked with mixins to verify the tag logic was executed prior to my logic) the issue perssisted.
any ideas why that could be? otherwise im just gonna experiment arround until i find a fix

**Comment by sisby-folk** [comment]
try installing Tinkerer's Smithing 2.6 - it'll log if you're causing the issue.

**Comment by Smartin-b** [comment]
i can check that im breaking it in local dev, if i comment my code out it stops breaking, i was just asking if you knew another reason that might be causing it other than beeing called prior to the tagregisterloader

**Comment by Smartin-b** [comment]
nvmd, figured it out, we accessed stuff from the worker thread

**Comment by Smartin-b** [comment]
fixed in latest release
