### ISSUE TITLE
Create Material Compatability

### ISSUE THREAD

**Issue by itsyourimp** [Truly-Modular/Modular-Item-API#30]
*Hey there, and thanks for making this mod series! After being spoilt by Construct's Armory, this is the only recent mod that has a full suite of customizable gear.*

Onto the request though, I noticed that Create's ingots, stone-type blocks (Limestone, Crimsite, Veridium, etc.), and Rose Quartz were missing from the autogenerated resources when it comes to Truly Modular. I can only assume it's because Create hasn't tagged these as variants of stone, which is how you got Diorite, Calcite and the like working. Again- all presumably, I'm no modmaker here.

If you get the time to, I'd love to see these implemented in some form or fashion!

**Comment by Smartin-b** [comment]
we are using the stone and wood tag to auto detect stuff

**Comment by Smartin-b** [comment]
there is a datapack on our discord for create compat
https://discord.gg/TebNhbCAUP
