### ISSUE TITLE
NPE with HT's Tree Chop

### ISSUE THREAD

**Issue by Bomb787** [Truly-Modular/Modular-Item-API#33]
**Describe the bug**
Looks like there's some kind of compat issue with HT's Tree Chop causing an NPE on startup.

**To Reproduce**
1. Install Forge
2. Install the latest versions of Architectury, Caelus API, HT's Tree Chop, and Modular Item API.
3. Try to start the game

**Expected behavior**
The game should start normally.

**Screenshots**
![image](https://github.com/Truly-Modular/Modular-Item-API/assets/39660651/aa3664a8-1139-43e9-8c82-dcb20983da90)

**Minecraft and Mod Version:**
Minecraft: 1.20.1
Forge/Fabric: 47.2.20
Miapi: Truly-Modular-miapi-forge-1.1.13-1.20.1
HT's Tree Chop: TreeChop-1.20.1-forge-0.19.0

**Full Mod List**
Architectury: 9.2.14-forge
Caelus API: Forge-3.1.0+1.20
HT's Tree Chop: Forge-0.19.0
Miapi: Forge-1.1.13-1.20.1

**Ingame Logs**
Debug: 
[debug.log](https://github.com/Truly-Modular/Modular-Item-API/files/14595196/debug.log)
Latest: 
[latest.log](https://github.com/Truly-Modular/Modular-Item-API/files/14595202/latest.log)
Crash Report: 
[crash-2024-03-13_20.35.39-fml.txt](https://github.com/Truly-Modular/Modular-Item-API/files/14595203/crash-2024-03-13_20.35.39-fml.txt)

**Comment by Smartin-b** [comment]
will be fixed in the next update, if you want a quick fix, its fixed in this snapshot
https://cdn.discordapp.com/attachments/1098169086275489823/1217670535564099644/Truly-Modular-miapi-1.1.13-1.20.1-snapshot-forge.jar?ex=6604df0e&is=65f26a0e&hm=bea55896ce6f9c1404da66c6028ba78c83380573073f51dab63172a2355ac938&

**Comment by JacquePott** [comment]
I tried the snapshot and it works on client, but when running a server I get a different error. I have confirmed it happens with the reproduction steps from the OP but only on a dedicated server.

 
[debug.log](https://github.com/Truly-Modular/Modular-Item-API/files/14649601/debug.log)
[latest.log](https://github.com/Truly-Modular/Modular-Item-API/files/14649602/latest.log)
[crash-2024-03-19_10.50.50-fml.txt](https://github.com/Truly-Modular/Modular-Item-API/files/14649604/crash-2024-03-19_10.50.50-fml.txt)

**Comment by Smartin-b** [comment]
https://cdn.discordapp.com/attachments/1098169086275489823/1219605150948134952/Truly-Modular-miapi-1.1.14-1.20.1-snapshot-forge.jar?ex=660be8cf&is=65f973cf&hm=e8b4e0e8fb22ac845476a75f2719d1f6dec7d7ef3f965bfdf953a1b3f6f6a02f&
oh, lol. that issue isnt caused bz HT Treechop, but by some other changes for the upcomming version

**Comment by Smartin-b** [comment]
before u use this snapshot u should backup your world,
it changes minor things abt nbt formating, making roling back to 1.1.13 not possible

**Comment by Smartin-b** [comment]
actually, some further issues were discovered with this snapshot, its probably better to rever 1.1.13 until 1.1.14 is ready to be released

**Comment by Smartin-b** [comment]
update is released
