### ISSUE TITLE
Truly-Modular API1.1.13,treechop0.19.0,forge47.2.14

### ISSUE THREAD

**Issue by Gai-fan** [Truly-Modular/Modular-Item-API#34]
[crash.txt](https://github.com/Truly-Modular/Modular-Item-API/files/14597833/crash.txt)

**Comment by Smartin-b** [comment]
https://github.com/Truly-Modular/Modular-Item-API/issues/33
duplicate

**Comment by Gai-fan** [comment]
Truly Modular is an exceptionally outstanding mod; however, it's regrettable that the weapons I've crafted utilizing Truly Modular are not compatible with the Better Paragliders mod.(Better Paragliders is a compatibility mod that implements the stamina system of Paragliders with Better Combat's attack mechanics.)https://modrinth.com/mod/better-paragliders

**Comment by Smartin-b** [comment]
https://github.com/Truly-Modular/Modular-Item-API/issues/35
duplicate
