### ISSUE TITLE
Incompatability with better paragliders (better combat botw-like stamina system)

### ISSUE THREAD

**Issue by DogeKingChris** [Truly-Modular/Modular-Item-API#35]
**Describe the Issue**
Some weapons don't drain stamina at all.

**The other mod/mods in Question**
Better Paragliders.

**Expected behavior**
When you swing a weapon with better paragliders installed, it is expected that the green stamina ring depletes. However, most modules do not work. I've had to delete truly modular from my modpack for the time being, which really sucks considering it was supposed to be a pretty neat and big part of it.

**Screenshots**
Doesn't really pertain to my problem.

**Additional context**
Nothing else.

**Comment by Smartin-b** [comment]
https://github.com/CravenCraft/BetterParagliders/issues/26
Not Truly Modulars fault, i reported the exact issue to Better Paragliders so they can fix it
