### ISSUE TITLE
Incompatibility with Fancy Dyes

### ISSUE THREAD

**Issue by mrcisdaduntman** [Truly-Modular/Modular-Item-API#36]
post on fancy dyes github page https://github.com/Haizor/fancy-dyes/issues/22
https://legacy.curseforge.com/minecraft/mc-mods/fancy-dyes

**Comment by Smartin-b** [comment]
compat with Fancy die might not be realistic, since truly modulars rendering is very far from vanillas

**Comment by mrcisdaduntman** [comment]
Oh.
