### ISSUE TITLE
Modded Wood types do not work

### ISSUE THREAD

**Issue by TheWackyman** [Truly-Modular/Modular-Item-API#40]
Modded wood types cannot be put in any place where vanilla wood is allowed

The mods I have seen this happen with so far are quark and twilight forest

I expect to be able to use modded wood types anywhere where I can use vanilla wood types, at least for the most part

**Comment by Smartin-b** [comment]
miapi 1.1.19 should fix this issue, if the issue still perssists please reapon the issue
