### ISSUE TITLE
Crashes when modifying chestplate/armor with Apotheosis affixes.

### ISSUE THREAD

**Issue by utterlynowhere** [Truly-Modular/Modular-Item-API#42]
Hi there! I've seen the newest update with the Apotheosis compat I immediately tried it out. When I place an armor with affinity (tested only from bosses so far, as I've no luck in finding them from loot chests) on a workbench, my game immediately crashes. [Here's my crash log on pastebin.](https://pastebin.com/vgubzEYU) 

Thank you very much!

**Comment by Smartin-b** [comment]
should be fixed in 1.1.21

**Comment by utterlynowhere** [comment]
Thanks for the quick update. Will be closing this issue now.
