### ISSUE TITLE
Game Crashing on World Load

### ISSUE THREAD

**Issue by QwertRvg** [Truly-Modular/Modular-Item-API#48]
**Describe the bug**
As the title says, the game crashes when a world is loaded and any Modular mod is added.

**To Reproduce**
1. Add a Modular mod
2. launch a world
(probably caused by another mod but unsure which)

**Expected behavior**
For the world to load correctly

**Minecraft and Mod Version:**
Minecraft: 1.20.1
Forge: 47.3.0
Miapi: 1.1.23

**Full Mod List**
dangerclose-merged-1.20.1-3.0.2.jar
draggable_lists-mc1.20-1.0.1-rev.824b2f3.jar
drizzleproof-1.20.1-2.0.0.jar
dungeons_plus-1.3.0-forge-1.20.1.jar
dyed-forge-1.20-1.1.2.jar
dynamiclightsreforged-1.20.1_v1.6.0.jar
dynamictrim-1.4.1-forge+1.20.1.jar
earthmobsmod-1.20.1-10.4.0.jar
elytra_physics-forge-2.0.jar
elytraslot-forge-6.4.0+1.20.1.jar
embeddium-0.3.20+mc1.20.1.jar
enemybanner-1.20.1-0.0.6.jar
EnhancedVisuals_FORGE_v1.8.1_mc1.20.1.jar
entity_model_features_forge_1.20.1-2.0.2.jar
entity_texture_features_forge_1.20.1-6.1.1.jar
entityculling-forge-1.6.6-mc1.20.1.jar
Etcetera-1.20.1-1.1.3-Forge.jar
etched-3.0.2.jar
ExpandedWorld-v1.2.0.jar
experienced_crops-1.20.1-1.1.0-forge.jar
Explorify v1.5.0 f10-48.jar
ExtraDetails for 1.20.1.jar
extragore-1.20.1-5.2.3.1.jar
extrasounds-1.20.1-forge-1.3.jar
fabric-api-0.92.2+1.11.8+1.20.1.jar
fabric-language-kotlin-1.10.20+kotlin.1.9.24.jar
fairylights-7.0.0-1.20.1.jar
Fallingleaves-1.20.1-2.1.0.jar
fallingtrees-0.12.1-forge-1.20.jar
FancyBlockParticles-1.20.1-forge-20.1.0.1-beta.jar
FarmersDelight-1.20.1-1.2.4.jar
fastconfigapi-1.1.0.jar
fastentitytransfer-forge-1.20-1.20.1-1.3.1.jar
FastFurnace-1.20.1-8.0.2.jar
Fastload-Reforged-mc1.20.1-3.4.0.jar
FastSuite-1.20.1-5.0.1.jar
FastWorkbench-1.20.1-8.0.4.jar
ferritecore-6.0.1-forge.jar
FiveHead-1.20.1-2.2.1.jar
flib-1.20.1-0.0.13.jar
footprintparticle-0.5.1-mc1.20.jar
ForgeConfigScreens-v8.0.2-1.20.1-Forge.jar
forgery-3.4.18+1.20.jar
FpsReducer2-forge-1.20-2.5.jar
framework-forge-1.20.1-0.7.6.jar
geckolib-forge-1.20.1-4.4.6.jar
Geophilic v2.4.1 f15-48.jar
globalnarrationtoggle-1.20.1-1.3.jar
glore_blocks.json
glore_brightness.json
glowingores-1.20.x-1.2.0.jar
gml-4.0.9-all.jar
GriddyZombie2.jar
guiclock-1.20.1-4.4.jar
guicompass-1.20.1-4.6.jar
HangGlider-v8.0.1-1.20.1-Forge.jar
hearths-v1.0.0.jar
hiddenrecipebook-1.20.1-4.6.jar
Highlighter-1.20.1-forge-1.1.9.jar
highlight-forge-1.20-2.0.1.jar
Iceberg-1.20.1-forge-1.1.21.jar
ImmediatelyFast-Forge-1.2.18+1.20.4.jar
inventoryessentials-forge-1.20.1-8.2.6.jar
inventoryhud.forge.1.20.1-3.4.22.jar
ironchest-1.20.1-14.4.4.jar
ItemPhysic_FORGE_v1.7.1_mc1.20.1.jar
Jade-1.20.1-forge-11.9.2.jar
jearchaeology-1.20.1-1.0.4.jar
jepp-1.20-1.1.2.jar
JustABaguette-v1.0.1-1.20.1-Forge.jar
justenoughbreeding-forge-1.20.x-1.2.1.jar
JustEnoughProfessions-forge-1.20.1-3.0.1.jar
JustEnoughResources-1.20.1-1.4.0.247.jar
justplayerheads-1.20.1-4.0.jar
KeepHeadNames-1.5.1-forge-1.19.3.jar
keepmysoiltilled-1.20.1-2.2.jar
kotlinforforge-4.11.0-all.jar
labellingcontainers-1.6.3.jar
LegendaryTooltips-1.20.1-forge-1.4.5.jar
LeonsBackportPaintings+M.1.20.1+ForM.2.0.0.jar
letmedespawn-forge-1.20.1-1.20.4-1.2.1.jar
limitedchunks-1.20.1-4.1.jar
lmft-1.0.4+1.20.1-forge.jar
logprot-1.20.1-3.4.jar
loot_journal-3.1.1.jar
lootr-forge-1.20-0.7.34.86.jar
map_atlases-1.20-6.0.7.jar
MaxHealthFix-Forge-1.20.1-12.0.3.jar
mcw-bridges-3.0.0-mc1.20.1forge.jar
mcw-doors-1.1.1forge-mc1.20.1.jar
memoryleakfix-forge-1.17+-1.1.5.jar
memorysettings-1.20.1-5.4.jar
midnightlib-forge-1.4.2.jar
modelfix-1.15.jar
modernfix-forge-5.18.1+mc1.20.1.jar
modlistscrollfix-1.0-1.20.1-FORGE.jar
monolib-forge-1.20.1-1.3.0.jar
moonlight-1.20-2.12.1-forge.jar
moreadvancementsmod-1.3.0-1.20.1.jar
moremobheads-0.2.1-1.20.1.jar
MouseTweaks-forge-mc1.20.1-2.25.1.jar
movingelevators-1.4.7-forge-mc1.20.1.jar
multimine-1.20.1.4.jar
musicmanager-1.20.1-1.3.15.jar
mvs-4.1.2-1.20-forge.jar
MyServerIsCompatible-1.20-1.0.jar
namepain-1.5.0 forge-1.20.x.jar
naturallychargedcreepers-1.20.1-3.4.jar
NBTac-FORGE-1.20.1-1.2.1.jar
nerb-1.20.1-0.3-FORGE.jar
NoAutoJump-1.20-1.0.jar
noisium-forge-2.0.3+mc1.20-1.20.1.jar
NotableBubbleText-1.20.1-1.0.5.jar
notenoughanimations-forge-1.7.4-mc1.20.1.jar
notenoughcrashes-4.4.7+1.20.1-forge.jar
nyfsspiders-forge-1.20.1-2.1.1.jar
oceanfloor-1.20.1-1.1.0.jar
oculus-mc1.20.1-1.7.0.jar
OpenBlocksTrophies-1.20.1-4.1.15.jar
optigui-2.1.7.jar
Oreganized 1.20.1-2.0.4.jar
overweightfarming-1.20.1-2.1.0-forge.jar
Paintings-forge-1.20.1-11.0.0.2.jar
paladin-furniture-mod-1.2.1-forge-mc1.20.1.jar
pandalib-0.2.1-forge-1.20.jar
panorama_screens-1.0+forge+mc1.20.jar
parry-2.5.0.jar
Patchouli-1.20.1-84-FORGE.jar
pathundergates-1.20.1-1.0.2-release.jar
personality-1.20.1-4.0.0.jar
phantasm-0.3.jar
phenomena-forge-1.20.1-3.4.jar
Philips-Ruins1.20.1-4.0.jar
piercearrow-1.20.1-5.0.0.jar
Placebo-1.20.1-8.6.2.jar
player-animation-lib-forge-1.0.2-rc1+1.20.jar
polymorph-forge-0.49.5+1.20.1.jar
Poofsounds5.3-1.20.1FORGE.jar
potacore-0.2.8-universal.jar
Prism-1.20.1-forge-1.0.5.jar
PuzzlesLib-v8.1.20-1.20.1-Forge.jar
Quark-4.0-458.jar
QuarkOddities-1.20.1.jar
Random Crits 1.3.2 - 1.20.1.jar
randomsheepcolours-1.20.1-3.3.jar
recipeessentials-1.20.1-3.4.jar
REIPluginCompatibilities-forge-12.0.93.jar
repurposed_structures-7.1.15+1.20.1-forge.jar
RoughlyEnoughItems-12.1.725-forge.jar
rrls-4.0.6.1+mc1.20.1-forge.jar
salt-1.20.1-1.2.5.jar
sawmill-1.20-1.4.2.jar
screenshot_viewer-1.3.2-forge-mc1.20.1.jar
screenshot-to-clipboard-1.0.9-forge.jar
Searchables-forge-1.20.1-1.0.3.jar
shutter-2.0.4-1.20.1.jar
Simple Weapons 1.4.5 - 1.20.1.jar
Simply-Improved-Terrain-Forge-1.20.1-0.5.4.0-alpha.jar
skinlayers3d-forge-1.6.6-mc1.20.1.jar
SkyVillages-1.0.4-1.19.2-1.20.1-forge-release.jar
SlotCycler-v8.0.1-1.20.1-Forge.jar
smoothboot(reloaded)-mc1.20.1-0.0.4.jar
smoothchunk-1.20.1-3.6.jar
snowundertrees-1.20.1-1.4.4.jar
soul-fire-d-forge-1.20.1-4.0.2.jar
sound-physics-remastered-forge-1.20.1-1.4.2.jar
spark-1.10.53-forge.jar
spelunkers_charm-3.6.0-1.20.1.jar
stackrefill-1.20.1-4.4.jar
stalkercreepers-1.20.1.1.jar
starlight-1.1.2+forge.1cda73c.jar
Structory_1.20.x_v1.3.5.jar
StylishEffects-v8.0.2-1.20.1-Forge.jar
SuggestionProviderFix-1.20.1-1.0.0.jar
superflatworldnoslimes-1.20.1-3.2.jar
supermartijn642configlib-1.1.8-forge-mc1.20.jar
supermartijn642corelib-1.1.17-forge-mc1.20.1.jar
supplementaries-1.20-2.8.15.jar
surfacemushrooms-1.20.1-3.3.jar
sword_trims-1.0.1.jar
table_top_craft-1.20.1-6.1.2.jar
TaxFreeLevels-1.3.13-forge-1.20.2.jar
themissingvillages-3.0.0-1.20.1-beta.jar
tia-1.20-1.1-forge.jar
Tiered-1.20.1-6.0.6-Forge.jar
Tips-Forge-1.20.1-12.0.5.jar
tntbreaksbedrock-1.20.1-3.2.jar
ToastControl-1.20.1-8.0.3.jar
ToolBelt-1.20.1-1.20.01.jar
ToroHealth-Unofficial-Forge-1.20.1-1.0.0.jar
trajectory_estimation-1.0.2-1.20.1.jar
transparent-forge-8.0.1+1.20.1.jar
trashslot-forge-1.20-15.1.0.jar
TravelersTitles-1.20-Forge-4.0.2.jar
trimmable-tools-mc1.20-v1.0.4.jar
Truly-Modular-miapi-forge-1.1.23-1.20.1.jar
Tumbleweed-forge-1.20.1-0.5.5.jar
UndergroundVillages-forge-1.20.1-2.1.0.jar
UnionLib-1.20.1-10.2.5-Forge.jar
Uppers-1.0.1.jar
valhelsia_core-forge-1.20.1-1.1.2.jar
valhelsia_structures-forge-1.20.1-1.1.2.jar
veinmining-forge-1.4.1+1.20.1.jar
visuality-forge-2.0.2.jar
VisualWorkbench-v8.0.0-1.20.1-Forge.jar
water-erosion-1.20.1-forge-1.1.6.jar
watut-forge-1.20.1-1.1.1.jar
weaponmaster_ydm-forge-1.20.1-4.2.3.jar
wits-1.1.0+1.20.1-forge.jar
wso16-forge-1.1.jar
YetAnotherConfigLib-3.5.0+1.20.1-forge.jar
YungsApi-1.20-Forge-4.0.5.jar
YungsBetterDungeons-1.20-Forge-4.0.4.jar
YungsBetterJungleTemples-1.20-Forge-2.0.5.jar
YungsBridges-1.20-Forge-4.0.3.jar
Zeta-1.0-19.jar
abridged-forge-1.20.x-1.1.1.jar
AchievementOptimizer-1.20.1-1.0.5.jar
AdvancementPlaques-1.20.1-forge-1.5.1.jar
AI-Improvements-1.20-0.5.2.jar
allurement-1.20.1-4.0.0.jar
AmbientSounds_FORGE_v6.0.2_mc1.20.1.jar
amendments-1.20-1.2.5.jar
amwplushies-forge-1.20.1-4.1.0.jar
AnimaticaReforged-1.20.1-0.1.3.jar
Apotheosis-1.20.1-7.3.5.jar
ApothicAttributes-1.20.1-1.3.5.jar
appleskin-forge-mc1.20.1-2.5.1.jar
architectury-9.2.14-forge.jar
artifacts-forge-9.5.11.jar
ash_api-forge-3.0.2+1.20.1.jar
auto_third_person-forge-1.20.1-2.1.jar
AxesAreWeapons-1.7.3-forge-1.20.2.jar
backpacked-forge-1.20.1-2.2.5.jar
badpackets-forge-0.4.3.jar
bagus_lib-1.20.1-4.6.0.jar
balm-forge-1.20.1-7.3.4-all.jar
bbs-1.20.1-0.1.3-forge.jar
beautifiedchatclient-1.20.1-2.5.jar
BetterAdvancements-1.20.1-0.3.2.162.jar
betterarcheology-1.1.9-1.20.1.jar
betterchunkloading-1.20.1-4.3.jar
bettercombat-forge-1.8.5+1.20.1.jar
BetterFog-1.20.1-1.2.2.jar
betterfpsdist-1.20.1-4.4.jar
BetterModsButton-v8.0.2-1.20.1-Forge.jar
BetterThirdPerson-Forge-1.20-1.9.0.jar
BiomeParticleWeather-v4.1.0-1.20.1-Forge.jar
blueprint-1.20.1-7.1.0.jar
blur-forge-3.1.1.jar
Bookshelf-Forge-1.20.1-20.2.13.jar
BorderlessWindow-1.20-1.6.0.jar
bounced-4.1.0-forge1.20.1.jar
caelus-forge-3.2.0+1.20.1.jar
camera-1.20.1-1.0.6.jar
canary-mc1.20.1-0.3.3.jar
carryon-forge-1.20.1-2.1.2.7.jar
ceilingtorch-1.20.1-1.29.jar
chat_heads-0.12.3-forge-1.20.jar
chunksending-1.20.1-2.8.jar
clickadv-1.20.1-3.8.jar
cloth-config-11.1.118-forge.jar
Clumps-forge-1.20.1-12.0.0.4.jar
cobweb-forge-1.20.1-1.0.0.jar
collective-1.20.1-7.62.jar
CompletionistsIndex-v8.0.0-1.20.1-Forge.jar
connectivity-1.20.1-5.5.jar
Connector-1.0.0-beta.44+1.20.1.jar
ConnectorExtras-1.11.1+1.20.1.jar
Controlling-forge-1.20.1-12.0.2.jar
coroutil-forge-1.20.1-1.3.7.jar
corpse-forge-1.20.1-1.0.12.jar
cosmeticarmorreworked-1.20.1-v1a.jar
CosmeticArmours - 1.3.7.1 - 1.20.1 - Forge.jar
CraftPresence-2.4.2+1.20.1.jar
CraterLib-Forge-1.20-2.0.0.jar
CreativeCore_FORGE_v2.11.30_mc1.20.1.jar
cupboard-1.20.1-2.6.jar
curios-forge-5.9.1+1.20.1.jar
curious_armor_stands-1.20-5.1.0.jar
customizableelytra-forge-2.1.2+1.20.jar
Truly-Modular-arsenal-arsenal-forge-1.8-1.20.1.jar

**Ingame Logs**
[latest.log](https://github.com/user-attachments/files/15931521/latest.log)

**Comment by Smartin-b** [comment]
sorry, but the log doesnt point to anything sensible, without you narrowing the cause down i cant do much

**Comment by QwertRvg** [comment]
oh alright
well i'll try narrowing it down then and come back to you

**Comment by Smartin-b** [comment]
any updates?

**Comment by Smartin-b** [comment]
does this issue still persist with the latest version of truly modular?

**Comment by Smartin-b** [comment]
I'm considering this fixed, if the issue still exists or reappears re-open this please
