### ISSUE TITLE
Greatsword charged attack does not inherit the sharpness enchantment.

### ISSUE THREAD

**Issue by CSNinja1** [Truly-Modular/Modular-Item-API#51]
When a modular greatsword is enchanted with sharpness, its charged attack does not inherit the damage given by that specific enchantment, meaning sharpness does not increase the damage of the greatsword's charged attack.

A video demonstrating what I am talking about:
https://github.com/user-attachments/assets/57497c7e-b949-4f1b-9d0c-f8953dd7feb9

**Comment by Smartin-b** [comment]
Huh. yeah, your right, enchantments arent currently allowed to modify output damage directly, this will be fixed in the next release

**Comment by Smartin-b** [comment]
https://modrinth.com/mod/modular-item-api/versions
release is out
