### ISSUE TITLE
Hide Armor/Invisible Armor Skin

### ISSUE THREAD

**Issue by Lightwave8** [Truly-Modular/Modular-Item-API#53]
(Fabric)
I use a mod for custom player models, and the Armor from Armory always shows on top of it.
I have tried alternative solutions, like cosmetic armor or a mod that turns armor invisible, but none have worked.

I would like to request the option to hide your armor.
Maybe as a Skin option when making the armor?

**Comment by Smartin-b** [comment]
the latest release should fix compat with cosmetic armor and other armor hide mods(as long as they utilize fabrics api for that)https://modrinth.com/mod/modular-item-api/versions
