### ISSUE TITLE
Simpleore copper tools

### ISSUE THREAD

**Issue by idk33333333** [Truly-Modular/Modular-Item-API#56]
**Describe the Issue**
Copper tools don't work, other materials from the same mod work fine, it just uses the copper ore already present in minecraft, and in fact you can use copper to customize other tools from other materials, weird

**The other mod/mods in Question**
https://www.curseforge.com/minecraft/mc-mods/simpleores

**Expected behavior**
Being able to edit copper tools

**Comment by Smartin-b** [comment]
nvmd the wont fix, it should be fixed in the latest release

**Comment by Smartin-b** [comment]
if not, please re-open this issue
