### ISSUE TITLE
Heavy Attack Doesn't Multiply Outgoing Damage

### ISSUE THREAD

**Issue by CSNinja1** [Truly-Modular/Modular-Item-API#58]
The Heavy Attack does not multiply the damage of the weapon properly when a mob is attacked with it.

Here is a video demonstrating the Issue.
https://github.com/user-attachments/assets/5eccf325-d9bf-456a-9b1e-fedbe17c7649

This is persistent through forge and fabric versions.

**Comment by CSNinja1** [comment]
Furthermore, the shield break attribute of the greatsword doesn't function with both regular and heavy attacks

Video for demonstration
https://github.com/user-attachments/assets/fccc63fd-93f1-4f48-8bb5-8a801dc6a2c9


It is possible that the target dummy with a shield that was used in the demonstration somehow worked differently to a player holding out a shield, meaning that against a player the shield break attribute might work as intended. I don't have another player to test that though.

**Comment by Smartin-b** [comment]
Shield break only works against players, this is intended this way

**Comment by CSNinja1** [comment]
ok, thank you for the conformation.

**Comment by Smartin-b** [comment]
the missing damage multiplication should be fixed in the next release

**Comment by Smartin-b** [comment]
what mod are you using that this happens to the enchanting glint?

**Comment by Smartin-b** [comment]
are you, by any chance, using really old versions of sodium?
if yes, you should upate, that issue is fixed on newer versions of sodium

**Comment by CSNinja1** [comment]
I am using the rubidium fork of sodium, and it seems to be no longer supported after a closer look. I'll likely replace it with Embeddium.
