### ISSUE TITLE
Crossbow's animation from BetterCombat not working

### ISSUE THREAD

**Issue by DP000-droid** [Truly-Modular/Modular-Item-API#59]
**Describe the Issue**
It seems the two-handed pose implemented in BetterCombat not carrying over to ModularAPI

**The other mod/mods in Question**
BetterCombat

**Expected behavior**
A working two-handed animation after loading an arrow into the crossbow

**Screenshots**
Expected behavior :
![2024-10-24_20 35 02](https://github.com/user-attachments/assets/586b1daa-2992-4108-839a-71d2dcafb1a7)

Current behavior :
![2024-10-24_20 35 12](https://github.com/user-attachments/assets/29cf0a30-556c-4c7c-9ffc-9d5590344abe)

**Additional context**
None.

**Comment by Smartin-b** [comment]
If I remember correctly, crossbows are currently all set to small animations, is that the current behavior or is the animation fully missing? Be aware that to use bc on a server with Miapis you sadly need a mod called better combat NBT fix , since bc refuses to fix a core bug breaking compat on servers

**Comment by DP000-droid** [comment]
Ah, I see. Many thanks for the response. I'll be sure to add the fix to my server.

**Comment by DP000-droid** [comment]
Ah hey, I installed the NBT fix and it still uses the small animations. The animation is not missing. Anyway I can modify it myself so all crossbows use "large crossbow" animation instead?

**Comment by Smartin-b** [comment]
While it's not super difficult to fix, it would require a data pack with a single Json, I'm currently only on mobile, if you wanna make the data pack urself I'd recommend joining the discord, other members can guide you through the process

**Comment by DP000-droid** [comment]
Alrighty, I think I can do it myself. Many thanks for the help and sorry for opening and closing issues.
