### ISSUE TITLE
1.20.1 MineColonies Incompatible (Forge)

### ISSUE THREAD

**Issue by Caritas-Dei** [Truly-Modular/Modular-Item-API#60]
**Describe the Issue**
From pressing Singleplayer with fresh install or from deleting existing world, eventual crash upon entering screen "Preparing for world creation..." which is then immediately followed by the "Saving world..." screen with MineColonies installed alongside Truly Modular API alone (with necessary dependencies for both mods). MineColonies' dependencies themselves are compatible with Truly Modular API and all other Truly Modular mods installed.

**The other mod/mods in Question**
Forge 47.3.11
Truly Modular API (1.1.31-1.20.1-neoforge)
MineColonies (minecolonies-1.20.1-1.1.697-snapshot.jar)
structurize
blockui
domum ornamentum

**Expected behavior**
~

**Screenshots**
~

**Additional context**
[crash-2024-10-27_02.14.03-client.txt](https://github.com/user-attachments/files/17532973/crash-2024-10-27_02.14.03-client.txt)

**Comment by Smartin-b** [comment]
It seems like due to mine colonies updates truly modulars compatibility code for it fails. Should be fixed soon, you can try to use older versions of mine colonies
