### ISSUE TITLE
FPS drop in Crafting Screen

### ISSUE THREAD

**Issue by FemBane** [Truly-Modular/Modular-Item-API#65]
**Describe the bug**
Framerate starts to drop after entering the crafting screen for items in the modular workbench.

**To Reproduce**
1. Open Modular Workbench
2. Click 'Create'
3. Click any item to create
4. Frame rate drops below 10 over a period of time.

**Screenshots**
![image](https://github.com/user-attachments/assets/081b2e0c-f4de-427f-b31d-7b7f3ae26664)
Entering any of the sub-menus for item creation starts the issue

**Minecraft and Mod Version:**
Minecraft: 1.20
Forge/Fabric: 47.3.6
Miapi: 1.1.36
other:

Spark Profiler: https://spark.lucko.me/iOW4hawhOX

Mod List: https://www.curseforge.com/minecraft/modpacks/dimension-meshi

Latest Log: https://mclo.gs/GPxJyF1

**Comment by Smartin-b** [comment]
Can you check if the bug is fixed with the UI-bugfixes / optimisations done in Miapi 1.1.37?

**Comment by Smartin-b** [comment]
With the recent ui optimisation I consider this resolved.
If the issue persists either re-open this or create a new issue.
