### ISSUE TITLE
enchant glint

### ISSUE THREAD

**Issue by ZZofa** [Truly-Modular/Modular-Item-API#66]
Enchant glint of modulared items is not the same as glint of vanilla items'.  It's obviously lighter.

Minecraft: 1.20.1-fabric0.16.9
Miapi:1.1.32
other:nope

video:https://github.com/user-attachments/assets/9b3f1126-1464-4533-a8c6-9322219dca05

**Comment by Smartin-b** [comment]
i changed the color to something more matching vanillas, but existing installs wont be changed by that, you would have to manually set the color in the config at the moment.
this is the RGBA i settled on A755FF80.

**Comment by ZZofa** [comment]
Can you just add a configuration option "use vanilla glint"?
(hmm i don't know whether fabric can just let special items use vanilla glint)
